export const rawGraphData: any = {
  "Akron Cleveland AOR": ["Belmont County BOR", "Steubenville BOR"],
  "All Jersey MLS, a dba": [
    "Nexus AOR Inc",
    "Mid Jersey AOR, Inc",
    "Ocean County Board of Realtors",
  ],
  "Altitude MLS": ["Realtors of Central Colorado"],
  "Ann Arbor Area Board of Realtors": [
    "Hillsdale County BOR - OLD",
    "Hillsdale County BOR",
  ],
  "Assn of Regina Realtors": [
    "Saskatchewan Rltrs Assn Inc - SK",
    "Prince Albert and District AOR",
    "Moose Jaw Real Estate Board",
    "RA of Lloydminster & District",
  ],
  "Battle Creek Area AOR": [
    "Hillsdale County BOR - OLD",
    "Jackson Area AOR",
    "Greater Lansing AOR",
  ],
  "Bay County Realtor Association": [
    "Midland Board of Realtors",
    "Saginaw Board of Realtors",
    "Central Michigan AOR",
  ],
  "Beckley Board of Realtors": [
    "Kanawha Valley Board of Realtors",
    "Mercer-Tazewell County BOR",
  ],
  "Belmont County BOR": [
    "Akron Cleveland AOR",
    "Portage County AOR",
    "Stark County AOR",
    "Warren Area Board of Realtors",
    "Youngstown Columbiana Assn",
    "Wayne-Holmes AOR",
    "Tuscarawas AOR",
    "Medina County BOR",
    "Lake and Geauga Area AOR",
    "Lorain County AOR",
  ],
  "Bibb Multi-List": [
    "Central Georgia MLS",
    "West Metro Board of Realtors",
    "Milledgeville MLS, a Baldwin dba",
    "Dublin Board of REALTORS",
    "First MLS",
    "Georgia MLS",
  ],
  "Branch County BOR": ["Hillsdale County BOR - OLD"],
  "Broward, Palm Bchs and St. Lucie": ["Meritage HB Coop 1"],
  "Brunswick County AOR": ["Lumberton Board of Realtors"],
  "Bucks County AOR": ["Gr Lehigh Valley Realtors", "Pocono Mountains AOR"],
  "Buffalo Niagara AOR": [
    "Upstate New York REIS - NY",
    "Chautauqua County BOR",
    "Otsego-Delaware BOR",
    "Central NY IS",
  ],
  "Cambria Somerset AOR": [
    "Greater Harrisburg AOR - PA",
    "West Penn Multi-List",
  ],
  "Carolina MLS dba Canopy MLS": ["Catawba Valley AOR", "Meritage HB Coop 1"],
  "Catawba Valley AOR": ["Carolina MLS dba Canopy MLS"],
  "Central Alberta RA": [
    "Grande Prairie Real Estate Board",
    "Medicine Hat Real Estate Board",
    "Fort McMurray REB Co-Op",
    "Lethbridge Real Estate Board",
    "RA of Lloydminster & District",
    "RA of South Central Alberta",
    "Realtors Association of Edmonton",
  ],
  "Central Georgia MLS": [
    "Milledgeville MLS, a Baldwin dba",
    "Dublin Board of REALTORS",
    "First MLS",
    "Georgia MLS",
    "Bibb Multi-List",
  ],
  "Central Michigan AOR": [
    "Midland Board of Realtors",
    "Bay County Realtor Association",
    "Saginaw Board of Realtors",
    "Traverse Area AOR",
    "Montcalm County AOR",
    "West Central AOR",
    "Greater Lansing AOR",
  ],
  "Central NY IS": [
    "Upstate New York REIS - NY",
    "Buffalo Niagara AOR",
    "Chautauqua County BOR",
    "Otsego-Delaware BOR",
  ],
  "Central Panhandle AOR - FL": [
    "Pensacola AOR",
    "Emerald Coast AOR",
    "Navarre Area Board of Realtors",
    "Chipola Area Board of Realtors",
    "Forgotten Coast REALTOR Assoc",
  ],
  "Chautauqua County BOR": [
    "Upstate New York REIS - NY",
    "Buffalo Niagara AOR",
    "Otsego-Delaware BOR",
    "Central NY IS",
  ],
  "Cherokee County BOR": ["Piedmont Regional AOR"],
  "Chipola Area Board of Realtors": [
    "Pensacola AOR",
    "Emerald Coast AOR",
    "Navarre Area Board of Realtors",
    "Central Panhandle AOR - FL",
  ],
  "Cleveland County AOR": ["Rutherford County BOR"],
  "Coastal Carolinas AOR": ["Meritage HB Coop 1"],
  "Coastal Plains AOR Inc - NC": ["Three Rivers MLS, Inc."],
  "Coeur D Alene AOR": ["NE Washington AOR"],
  "Columbia Basin BOR": ["Umatilla County BOR"],
  "Coop Arkansas Realtors MLS": [
    "Paragould Board of REALTORS",
    "Northeast Arkansas BOR",
    "West Memphis Board of REALTORS",
  ],
  "Dalton MLS Inc.": [
    "Greater Chattanooga AOR",
    "River Counties AOR",
    "First MLS",
    "Georgia MLS",
  ],
  "Daytona Beach Area AOR": [
    "St Augustine and St Johns Co",
    "Space Coast AOR",
    "Ocala Marion County AOR",
    "Northeast Florida AOR",
    "Hernando County AOR",
  ],
  "Dublin Board of REALTORS": [
    "Central Georgia MLS",
    "First MLS",
    "Georgia MLS",
    "Bibb Multi-List",
  ],
  "Durango Area AOR": [
    "Pagosa Area AOR",
    "Gunnison-Crested Butte AOR",
    "Four Corners Board of Realtors",
    "Four Corners BOR",
  ],
  "East Tennessee Realtors - TN": [
    "Tennessee Virginia Regional MLS",
    "Greater Chattanooga AOR",
    "River Counties AOR",
    "Upper Cumberland AOR",
    "Lakeway Area Assn of REALTORS",
    "Great Smoky Mountains AOR",
  ],
  "Emerald Coast AOR": [
    "Pensacola AOR",
    "Central Panhandle AOR - FL",
    "Chipola Area Board of Realtors",
    "Forgotten Coast REALTOR Assoc",
  ],
  "Fayette-Nicholas BOR": [
    "Kanawha Valley Board of Realtors",
    "Mercer-Tazewell County BOR",
  ],
  "First MLS": [
    "Greater Chattanooga AOR",
    "Central Georgia MLS",
    "West Metro Board of Realtors",
    "Milledgeville MLS, a Baldwin dba",
    "Dalton MLS Inc.",
    "Dublin Board of REALTORS",
    "Bibb Multi-List",
  ],
  "Forgotten Coast REALTOR Assoc": [
    "Pensacola AOR",
    "Emerald Coast AOR",
    "Navarre Area Board of Realtors",
    "Central Panhandle AOR - FL",
  ],
  "Fort McMurray REB Co-Op": [
    "Grande Prairie Real Estate Board",
    "Medicine Hat Real Estate Board",
    "Lethbridge Real Estate Board",
    "RA of Lloydminster & District",
    "RA of South Central Alberta",
    "Central Alberta RA",
    "Realtors Association of Edmonton",
  ],
  "Four Corners Board of Realtors": [
    "Durango Area AOR",
    "Pagosa Area AOR",
    "Gunnison-Crested Butte AOR",
  ],
  "Four Corners BOR": [
    "Durango Area AOR",
    "Pagosa Area AOR",
    "Gunnison-Crested Butte AOR",
  ],
  "Franklin Board of Realtors": ["Northern Jackson Co MLS"],
  "Fredericton Real Estate Board": [
    "Greater Moncton REB",
    "Saint John Real Estate Board",
  ],
  "Georgia MLS": [
    "Central Georgia MLS",
    "West Metro Board of Realtors",
    "Milledgeville MLS, a Baldwin dba",
    "Dalton MLS Inc.",
    "Dublin Board of REALTORS",
    "Bibb Multi-List",
  ],
  "Gr Hazleton Assoc of Realtors": [
    "Lancaster County AOR",
    "Gr Lehigh Valley Realtors",
    "Greater Scranton BOR",
    "Luzerne County AOR a dba - PA",
    "Pike Wayne AOR",
  ],
  "Gr Lehigh Valley Realtors": [
    "Lancaster County AOR",
    "Tri County Suburban Rltrs - PA",
    "Bucks County AOR",
    "Tri County Suburban Rltrs -M -PA",
    "Greater Philadelphia AOR",
    "Greater Harrisburg AOR - PA",
    "Reading Berks AOR",
    "Greater Scranton BOR",
    "Pocono Mountains AOR",
    "Pike Wayne AOR",
    "Gr Hazleton Assoc of Realtors",
  ],
  "Gr. New Haven Assoc of Rltrs": ["Smart MLS"],
  "Grand Rapids AOR": ["Hillsdale County BOR - OLD", "Greater Lansing AOR"],
  "Grande Prairie Real Estate Board": [
    "Medicine Hat Real Estate Board",
    "Fort McMurray REB Co-Op",
    "Lethbridge Real Estate Board",
    "RA of Lloydminster & District",
    "RA of South Central Alberta",
    "Central Alberta RA",
    "Realtors Association of Edmonton",
  ],
  "Great Smoky Mountains AOR": [
    "Tennessee Virginia Regional MLS",
    "Greater Chattanooga AOR",
    "East Tennessee Realtors - TN",
    "Lakeway Area Assn of REALTORS",
  ],
  "Greater Chattanooga AOR": [
    "Tennessee Virginia Regional MLS",
    "East Tennessee Realtors - TN",
    "River Counties AOR",
    "Upper Cumberland AOR",
    "Lakeway Area Assn of REALTORS",
    "Great Smoky Mountains AOR",
    "Dalton MLS Inc.",
    "First MLS",
  ],
  "Greater Harrisburg AOR - PA": [
    "Cambria Somerset AOR",
    "Gr Lehigh Valley Realtors",
    "Pocono Mountains AOR",
    "West Penn Multi-List",
  ],
  "Greater Hartford AOR": ["Smart MLS"],
  "Greater Lansing AOR": [
    "Midland Board of Realtors",
    "Saginaw Board of Realtors",
    "Central Michigan AOR",
    "Shiawassee Regional BOR",
    "Jackson Area AOR",
    "Battle Creek Area AOR",
    "West Michigan Lakeshore AOR",
    "Southwestern Michigan AOR",
    "Grand Rapids AOR",
    "Montcalm County AOR",
    "West Central AOR",
  ],
  "Greater Moncton REB": [
    "Fredericton Real Estate Board",
    "Saint John Real Estate Board",
  ],
  "Greater Philadelphia AOR": [
    "Gr Lehigh Valley Realtors",
    "Pocono Mountains AOR",
  ],
  "Greater Pocatello AOR": ["Snake River Regional MLS"],
  "Greater Scranton BOR": [
    "Gr Lehigh Valley Realtors",
    "Pocono Mountains AOR",
    "Pike Wayne AOR",
    "Gr Hazleton Assoc of Realtors",
  ],
  "Greater Tampa AOR": ["Northeast Florida AOR"],
  "Greater Waterbury BOR": ["Smart MLS"],
  "Gunnison-Crested Butte AOR": [
    "Durango Area AOR",
    "Pagosa Area AOR",
    "Four Corners Board of Realtors",
    "Four Corners BOR",
  ],
  "Haywood County Keyboxes": ["NCMMLS, a dba"],
  "Hernando County AOR": [
    "St Augustine and St Johns Co",
    "Space Coast AOR",
    "Daytona Beach Area AOR",
    "Northeast Florida AOR",
    "Realtors Assoc of Citrus County",
  ],
  "Hillsdale County BOR": [
    "Jackson Area AOR",
    "Ann Arbor Area Board of Realtors",
  ],
  "Hillsdale County BOR - OLD": [
    "Jackson Area AOR",
    "Ann Arbor Area Board of Realtors",
    "Branch County BOR",
    "Battle Creek Area AOR",
    "West Michigan Lakeshore AOR",
    "Southwestern Michigan AOR",
    "St Joseph County AOR",
    "Grand Rapids AOR",
    "Mason Oceana Manistee BOR",
    "Montcalm County AOR",
    "West Central AOR",
  ],
  "HUD - POD1": ["Supra Marketing Samples"],
  "Intermountain MLS": ["Mini Cassia MLS"],
  "Iron County Board of Realtors": ["Washington County BOR"],
  "Jackson Area AOR": [
    "Midland Board of Realtors",
    "Hillsdale County BOR - OLD",
    "Battle Creek Area AOR",
    "St Joseph County AOR",
    "Hillsdale County BOR",
    "Greater Lansing AOR",
  ],
  "Kanawha Valley Board of Realtors": [
    "Beckley Board of Realtors",
    "Fayette-Nicholas BOR",
    "Mercer-Tazewell County BOR",
    "Parkersburg Area Assn of Rltrs",
  ],
  "Kent County AOR": ["New Castle County BOR"],
  "Lake and Geauga Area AOR": ["Belmont County BOR"],
  "Lakeway Area Assn of REALTORS": [
    "Tennessee Virginia Regional MLS",
    "Greater Chattanooga AOR",
    "SW Virginia Assoc of Rltrs",
    "East Tennessee Realtors - TN",
    "River Counties AOR",
    "Great Smoky Mountains AOR",
  ],
  "Lancaster County AOR": [
    "Gr Lehigh Valley Realtors",
    "Gr Hazleton Assoc of Realtors",
  ],
  "Lethbridge Real Estate Board": [
    "Grande Prairie Real Estate Board",
    "Medicine Hat Real Estate Board",
    "Fort McMurray REB Co-Op",
    "RA of Lloydminster & District",
    "RA of South Central Alberta",
    "Central Alberta RA",
    "Realtors Association of Edmonton",
  ],
  "Lorain County AOR": ["Belmont County BOR"],
  "Lower Yakima Valley MLS": ["Tri City Association of Realtors"],
  "Lumberton Board of Realtors": ["Brunswick County AOR"],
  "Martin and Tope RE Company": ["Realtors of Central Colorado"],
  "Martin County of Treasure Coast": ["RA of Martin County (old)"],
  "Mason Oceana Manistee BOR": ["Hillsdale County BOR - OLD"],
  "Medicine Hat Real Estate Board": [
    "Grande Prairie Real Estate Board",
    "Fort McMurray REB Co-Op",
    "Lethbridge Real Estate Board",
    "RA of Lloydminster & District",
    "RA of South Central Alberta",
    "Central Alberta RA",
    "Realtors Association of Edmonton",
  ],
  "Melbourne Area AOR": ["Space Coast AOR", "MLS of Brevard"],
  "Mercer-Tazewell County BOR": [
    "SW Virginia Assoc of Rltrs",
    "Beckley Board of Realtors",
    "Fayette-Nicholas BOR",
    "Kanawha Valley Board of Realtors",
  ],
  "Meritage HB Coop 1": [
    "Carolina MLS dba Canopy MLS",
    "Coastal Carolinas AOR",
    "Broward, Palm Bchs and St. Lucie",
    "Northeast Florida AOR",
  ],
  "Mid Jersey AOR, Inc": [
    "All Jersey MLS, a dba",
    "Ocean County Board of Realtors",
  ],
  "Mid-State Association of Rltrs": ["Smart MLS"],
  "Midland Board of Realtors": [
    "Bay County Realtor Association",
    "Saginaw Board of Realtors",
    "Central Michigan AOR",
    "Jackson Area AOR",
    "Greater Lansing AOR",
  ],
  "Milledgeville MLS, a Baldwin dba": [
    "Central Georgia MLS",
    "First MLS",
    "Georgia MLS",
    "Bibb Multi-List",
  ],
  "Mini Cassia MLS": ["Intermountain MLS"],
  "MLS of Brevard": ["Melbourne Area AOR"],
  "Monmouth County AOR": ["Nexus AOR Inc", "Ocean County Board of Realtors"],
  "Montcalm County AOR": [
    "Hillsdale County BOR - OLD",
    "Central Michigan AOR",
    "Greater Lansing AOR",
  ],
  "Moose Jaw Real Estate Board": [
    "Saskatchewan Rltrs Assn Inc - SK",
    "Prince Albert and District AOR",
    "Assn of Regina Realtors",
  ],
  "Mountain Lakes Board of Realtors": ["NE Georgia Bd of Rltrs"],
  "Navarre Area Board of Realtors": [
    "Pensacola AOR",
    "Central Panhandle AOR - FL",
    "Chipola Area Board of Realtors",
    "Forgotten Coast REALTOR Assoc",
  ],
  "NCMMLS, a dba": ["Haywood County Keyboxes", "Rutherford County BOR"],
  "NE Georgia Bd of Rltrs": ["Mountain Lakes Board of Realtors"],
  "NE Washington AOR": ["Spokane Association of Realtors", "Coeur D Alene AOR"],
  "New Castle County BOR": ["Nexus AOR Inc", "Kent County AOR"],
  "New Haven Middlesex AOR": ["Smart MLS"],
  "Nexus AOR Inc": [
    "New Castle County BOR",
    "All Jersey MLS, a dba",
    "Ocean County Board of Realtors",
    "Monmouth County AOR",
  ],
  "Northeast Arkansas BOR": [
    "Coop Arkansas Realtors MLS",
    "Paragould Board of REALTORS",
    "West Memphis Board of REALTORS",
  ],
  "Northeast Florida AOR": [
    "Meritage HB Coop 1",
    "St Augustine and St Johns Co",
    "Space Coast AOR",
    "Daytona Beach Area AOR",
    "Greater Tampa AOR",
    "Pinellas Realtor Organization",
    "Hernando County AOR",
  ],
  "Northern Jackson Co MLS": ["Franklin Board of Realtors"],
  "Northwest MLS": ["Walla Walla AOR"],
  "Ocala Marion County AOR": ["Daytona Beach Area AOR"],
  "Ocean County Board of Realtors": [
    "All Jersey MLS, a dba",
    "Nexus AOR Inc",
    "Mid Jersey AOR, Inc",
    "South Monmouth Board of Realtors",
    "Monmouth County AOR",
  ],
  "ODS Central Oregon - OR": [
    "ODS Southern Oregon - OR",
    "ODS Klamath Area - OR",
  ],
  "ODS Klamath Area - OR": [
    "ODS Southern Oregon - OR",
    "ODS Central Oregon - OR",
  ],
  "ODS Southern Oregon - OR": [
    "ODS Klamath Area - OR",
    "ODS Central Oregon - OR",
  ],
  "Otsego-Delaware BOR": [
    "Upstate New York REIS - NY",
    "Buffalo Niagara AOR",
    "Chautauqua County BOR",
    "Central NY IS",
  ],
  "Pagosa Area AOR": [
    "Durango Area AOR",
    "Realtors of Central Colorado",
    "Gunnison-Crested Butte AOR",
    "Four Corners Board of Realtors",
    "Four Corners BOR",
  ],
  "Paragould Board of REALTORS": [
    "Coop Arkansas Realtors MLS",
    "Northeast Arkansas BOR",
    "West Memphis Board of REALTORS",
  ],
  "Parkersburg Area Assn of Rltrs": ["Kanawha Valley Board of Realtors"],
  "Pegasus Beta": ["Supra Marketing Samples"],
  "Pegasus Dry Run 1": ["Supra Marketing Samples"],
  "Pensacola AOR": [
    "Emerald Coast AOR",
    "Navarre Area Board of Realtors",
    "Central Panhandle AOR - FL",
    "Chipola Area Board of Realtors",
    "Forgotten Coast REALTOR Assoc",
  ],
  "Piedmont Regional AOR": ["Cherokee County BOR"],
  "Pike Wayne AOR": [
    "Gr Lehigh Valley Realtors",
    "Greater Scranton BOR",
    "Pocono Mountains AOR",
  ],
  "Pikes Peak Realtor Services": [
    "Royal Gorge AOR",
    "Pueblo Association of Realtors",
    "Realtors of Central Colorado",
  ],
  "Pinellas Realtor Organization": ["Northeast Florida AOR"],
  "Pocono Mountains AOR": [
    "Tri County Suburban Rltrs - PA",
    "Bucks County AOR",
    "Tri County Suburban Rltrs -M -PA",
    "Greater Philadelphia AOR",
    "Greater Harrisburg AOR - PA",
    "Reading Berks AOR",
    "Gr Lehigh Valley Realtors",
    "Greater Scranton BOR",
    "Pike Wayne AOR",
  ],
  "Portage County AOR": ["Belmont County BOR"],
  PrimeMLS: ["Vermont REIN"],
  "Prince Albert and District AOR": [
    "Saskatchewan Rltrs Assn Inc - SK",
    "Moose Jaw Real Estate Board",
    "RA of Lloydminster & District",
    "Assn of Regina Realtors",
  ],
  "Pueblo Association of Realtors": [
    "Royal Gorge AOR",
    "Realtors of Central Colorado",
  ],
  "RA of Lake and Sumter Counties": ["Realtors Assoc of Citrus County"],
  "RA of Lloydminster & District": [
    "Saskatchewan Rltrs Assn Inc - SK",
    "Grande Prairie Real Estate Board",
    "Prince Albert and District AOR",
    "Medicine Hat Real Estate Board",
    "Fort McMurray REB Co-Op",
    "Lethbridge Real Estate Board",
    "RA of South Central Alberta",
    "Assn of Regina Realtors",
    "Central Alberta RA",
    "Realtors Association of Edmonton",
  ],
  "RA of Martin County (old)": [
    "Regional MLS",
    "Martin County of Treasure Coast",
    "Broward, Palm Bchs and St. Lucie",
  ],
  "RA of South Central Alberta": [
    "Grande Prairie Real Estate Board",
    "Medicine Hat Real Estate Board",
    "Fort McMurray REB Co-Op",
    "Lethbridge Real Estate Board",
    "RA of Lloydminster & District",
    "Central Alberta RA",
    "Realtors Association of Edmonton",
  ],
  "Reading Berks AOR": ["Gr Lehigh Valley Realtors", "Pocono Mountains AOR"],
  "Realtors Assoc of Citrus County": [
    "RA of Lake and Sumter Counties",
    "Hernando County AOR",
  ],
  "Realtors Association of Edmonton": [
    "Grande Prairie Real Estate Board",
    "Medicine Hat Real Estate Board",
    "Fort McMurray REB Co-Op",
    "Lethbridge Real Estate Board",
    "RA of Lloydminster & District",
    "RA of South Central Alberta",
    "Central Alberta RA",
  ],
  "Realtors of Central Colorado": [
    "Altitude MLS",
    "Pagosa Area AOR",
    "Royal Gorge AOR",
    "Pueblo Association of Realtors",
  ],
  "Regional MLS": ["RA of Martin County (old)"],
  "River Counties AOR": [
    "Greater Chattanooga AOR",
    "East Tennessee Realtors - TN",
    "Upper Cumberland AOR",
    "Lakeway Area Assn of REALTORS",
    "Dalton MLS Inc.",
  ],
  "Royal Gorge AOR": [
    "Pikes Peak Realtor Services",
    "Pueblo Association of Realtors",
    "Realtors of Central Colorado",
  ],
  "Rutherford County BOR": ["NCMMLS, a dba", "Cleveland County AOR"],
  "Saginaw Board of Realtors": [
    "Midland Board of Realtors",
    "Bay County Realtor Association",
    "Central Michigan AOR",
    "Shiawassee Regional BOR",
    "Greater Lansing AOR",
  ],
  "Saint John Real Estate Board": [
    "Greater Moncton REB",
    "Fredericton Real Estate Board",
  ],
  "Saskatchewan Rltrs Assn Inc - SK": [
    "Prince Albert and District AOR",
    "Moose Jaw Real Estate Board",
    "RA of Lloydminster & District",
    "Assn of Regina Realtors",
  ],
  "Shiawassee Regional BOR": [
    "Saginaw Board of Realtors",
    "Greater Lansing AOR",
  ],
  "Smart MLS": [
    "Greater Hartford AOR",
    "New Haven Middlesex AOR",
    "Greater Waterbury BOR",
    "Gr. New Haven Assoc of Rltrs",
    "Mid-State Association of Rltrs",
  ],
  "Snake River Regional MLS": ["Greater Pocatello AOR"],
  "South Monmouth Board of Realtors": ["Ocean County Board of Realtors"],
  "Southwestern Michigan AOR": [
    "Hillsdale County BOR - OLD",
    "Greater Lansing AOR",
  ],
  "Space Coast AOR": [
    "St Augustine and St Johns Co",
    "Daytona Beach Area AOR",
    "Northeast Florida AOR",
    "Hernando County AOR",
  ],
  "Spokane Association of Realtors": ["NE Washington AOR"],
  "St Augustine and St Johns Co": [
    "Space Coast AOR",
    "Daytona Beach Area AOR",
    "Northeast Florida AOR",
    "Hernando County AOR",
  ],
  "St Joseph County AOR": ["Hillsdale County BOR - OLD", "Jackson Area AOR"],
  "Stark County AOR": ["Belmont County BOR"],
  "Steubenville BOR": ["Akron Cleveland AOR"],
  "Supra Marketing Samples": ["HUD - POD1", "Pegasus Dry Run 1"],
  "SW Virginia Assoc of Rltrs": [
    "Tennessee Virginia Regional MLS",
    "Lakeway Area Assn of REALTORS",
    "Mercer-Tazewell County BOR",
  ],
  "Tennessee Virginia Regional MLS": [
    "East Tennessee Realtors - TN",
    "Lakeway Area Assn of REALTORS",
    "Great Smoky Mountains AOR",
    "Greater Chattanooga AOR",
    "SW Virginia Assoc of Rltrs",
  ],
  "Test Member John Valdez": ["TestPegasusOnly"],
  TestPegasusOnly: ["Test Member John Valdez"],
  "Three Rivers MLS, Inc.": ["Coastal Plains AOR Inc - NC"],
  "Traverse Area AOR": ["Central Michigan AOR"],
  "Tri City Association of Realtors": ["Lower Yakima Valley MLS"],
  "Tri County Suburban Rltrs - PA": [
    "Gr Lehigh Valley Realtors",
    "Pocono Mountains AOR",
  ],
  "Tri County Suburban Rltrs -M -PA": [
    "Gr Lehigh Valley Realtors",
    "Pocono Mountains AOR",
  ],
  "Tri-County BOR": ["West Penn Multi-List"],
  "Tuscarawas AOR": ["Belmont County BOR"],
  "Umatilla County BOR": ["Columbia Basin BOR"],
  "Upper Cumberland AOR": [
    "East Tennessee Realtors - TN",
    "River Counties AOR",
    "Greater Chattanooga AOR",
  ],
  "Upstate New York REIS - NY": [
    "Buffalo Niagara AOR",
    "Chautauqua County BOR",
    "Otsego-Delaware BOR",
    "Central NY IS",
  ],
  "Vancouver Island REB": ["Victoria REB"],
  "Vermont REIN": ["PrimeMLS"],
  "Victoria REB": ["Vancouver Island REB"],
  "Walla Walla AOR": ["Northwest MLS"],
  "Warren Area Board of Realtors": ["Belmont County BOR"],
  "Washington County BOR": ["Iron County Board of Realtors"],
  "Wayne-Holmes AOR": ["Belmont County BOR"],
  "West Central AOR": [
    "Hillsdale County BOR - OLD",
    "Central Michigan AOR",
    "Greater Lansing AOR",
    "MLS of Springfield Realtors",
    "Kansas City Regional AOR",
    "Central Missouri Board of Rltrs",
    "Ozarks Board of Realtors",
  ],
  "West Memphis Board of REALTORS": [
    "Coop Arkansas Realtors MLS",
    "Paragould Board of REALTORS",
    "Northeast Arkansas BOR",
  ],
  "West Metro Board of Realtors": [
    "First MLS",
    "Georgia MLS",
    "Bibb Multi-List",
  ],
  "West Michigan Lakeshore AOR": [
    "Hillsdale County BOR - OLD",
    "Greater Lansing AOR",
  ],
  "West Penn Multi-List": [
    "Greater Harrisburg AOR - PA",
    "Cambria Somerset AOR",
    "Tri-County BOR",
  ],
  "Youngstown Columbiana Assn": ["Belmont County BOR"],
  "Gr Fort Worth Assoc of Rltrs": [
    "Texoma 2",
    "Heartland AOR",
    "Houston Association of Realtors",
  ],
  "Gr Louisville Assoc of Realtors": ["Lexington Bluegrass AOR"],
  "Gr NW Indiana AOR and Laporte": [
    "South Bend Area Realtors Inc",
    "North Central Indiana AOR",
  ],
  "Gr Owensboro Rltrs Association": ["Henderson Audubon BOR"],
  "Granbury Association of Realtors": [
    "Meritage HB Coop 2",
    "Waco Association of Realtors",
    "Texoma 2",
    "Houston Association of Realtors",
  ],
  "Grand Prairie Board of Realtors": ["Heartland AOR"],
  "Great Plains MLS Omaha": ["SW Iowa Assoc of Realtors"],
  "Greater Alabama MLS": [
    "Huntsville Area AOR",
    "Marshall County BOR",
    "Morgan County AOR",
    "Etowah/Cherokee County AOR",
    "Calhoun Cty Area BOR",
  ],
  "Greater Augusta AOR": ["Rockbridge Highlands Realtors"],
  "Greater Augusta BOR": ["Aiken Association of Realtors"],
  "Greater Gateway AOR": ["Central Illinois BOR, Inc - IL"],
  "Greater La Crosse Area MLS Corp": ["South Central Wisconsin MLS"],
  "Greater McAllen AOR": [
    "Harlingen Board of Realtors",
    "Brownsville South Padre BOR",
  ],
  "Greater Metro West AOR, a dba": [
    "Greater Tyler AOR",
    "Waco Association of Realtors",
    "Texoma 2",
    "Heartland AOR",
  ],
  "Greater Palm Springs - CA": [
    "Ventura County Coastal AOR",
    "Conejo Simi Moorpark AOR",
    "Simi Valley-Moorpark AOR, Inc.",
    "Desert Communities-Old",
    "Palos Verdes Peninsula AOR",
    "Inglewood Board of Realtors",
    "South Bay AOR",
    "Pasadena-Foothills AOR",
    "Glendale Association of Realtors",
    "Arcadia Association of Realtors",
    "Montebello Assoc of Realtors",
    "West San Gabriel Valley Realtors",
    "Tri-Counties AOR",
    "Citrus Valley AOR",
    "Inland Valleys AOR - CA",
    "The Inland Gateway a dba - EVAR",
    "SW Riverside Assoc of Rltrs",
    "The Inland Gateway a dba - TIGAR",
    "Orange County Realtors - CA",
    "Laguna Board of Realtors",
    "Downey Association of Realtors",
    "Rancho Southeast AOR",
    "Pac West AOR",
    "Orange Coast AOR",
    "Joshua Tree Gateway AOR",
    "Pacific Southwest AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "CLAW-Combined LA Westside MLS",
  ],
  "Greater Texoma AOR": [
    "Greater Tyler AOR",
    "Waco Association of Realtors",
    "Texoma 2",
    "Heartland AOR",
  ],
  "Greater Tyler AOR": [
    "Longview Area AOR",
    "Waco Association of Realtors",
    "Gr Fort Worth Assoc of Rltrs",
    "Gr Denton-Wise Assoc of Rltrs",
    "Arlington Board of Realtors",
    "Greater Metro West AOR, a dba",
    "Johnson County AOR",
    "Greater Texoma AOR",
    "Lake Cities AOR",
    "MetroTex Key Services",
    "Collin County Area Realtors, Inc",
    "N Texas RE Technical Services",
    "Stephenville AOR",
  ],
  "Green Valley/Sahuarita AOR": [
    "MLS of So AZ",
    "Southeast Arizona AOR",
    "Santa Cruz County MLS",
    "Douglas Association of Realtors",
  ],
  "Gulf South REIN": [
    "Gr Baton Rouge Assoc of Rltrs",
    "Realtor Association of Acadiana",
    "Northshore Area BOR",
    "Bayou Board of Realtors",
  ],
  "Harlingen Board of Realtors": [
    "Greater McAllen AOR",
    "Brownsville South Padre BOR",
  ],
  "Heartland AOR": [
    "Gr Fort Worth Assoc of Rltrs",
    "Gr Denton-Wise Assoc of Rltrs",
    "Arlington Board of Realtors",
    "Grand Prairie Board of Realtors",
    "Greater Metro West AOR, a dba",
    "Johnson County AOR",
    "Greater Texoma AOR",
    "MetroTex Key Services",
    "Collin County Area Realtors, Inc",
    "Ellis Hill County AOR",
    "N Texas RE Technical Services",
    "Stephenville AOR",
    "Houston Association of Realtors",
  ],
  "Henderson Audubon BOR": ["Gr Owensboro Rltrs Association"],
  "High Desert AOR": [
    "Coastal Mendocino AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "Barstow Association of Realtors",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Silicon Valley AOR OLD",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
    "Palos Verdes Peninsula AOR",
    "Inglewood Board of Realtors",
    "South Bay AOR",
    "Pasadena-Foothills AOR",
    "Arcadia Association of Realtors",
    "Montebello Assoc of Realtors",
    "West San Gabriel Valley Realtors",
    "Tri-Counties AOR",
    "Citrus Valley AOR",
    "Inland Valleys AOR - CA",
    "The Inland Gateway a dba - EVAR",
    "SW Riverside Assoc of Rltrs",
    "The Inland Gateway a dba - TIGAR",
    "Orange County Realtors - CA",
    "Laguna Board of Realtors",
    "Downey Association of Realtors",
    "Rancho Southeast AOR",
    "Pac West AOR",
    "Orange Coast AOR",
    "Joshua Tree Gateway AOR",
    "North San Diego Co Assn of Rltrs",
    "Pacific Southwest AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "CLAW-Combined LA Westside MLS",
    "California Desert AOR",
  ],
  "Highland Lakes AOR": ["Unlock MLS a dba of ACTRIS"],
  "Houston Association of Realtors": [
    "Unlock MLS a dba of ACTRIS",
    "Galveston AOR",
    "San Antonio Board of Realtors",
    "Tall Pines AOR - TX",
    "Heartland AOR",
    "Gr Fort Worth Assoc of Rltrs",
    "Gr Denton-Wise Assoc of Rltrs",
    "Arlington Board of Realtors",
    "Granbury Association of Realtors",
    "Collin County Area Realtors, Inc",
  ],
  "Huntsville Area AOR": [
    "Greater Alabama MLS",
    "Etowah/Cherokee County AOR",
    "Calhoun Cty Area BOR",
  ],
  "Indiana Regional MLS": [
    "Bloomington MLS",
    "South Bend Area Realtors Inc",
    "Lafayette Regional BOR",
    "Kosciusko Board of Realtors",
    "Northeastern Indiana AOR",
    "North Central Indiana AOR",
    "Elkhart County Board of Realtors",
  ],
  "Inglewood Board of Realtors": [
    "Coastal Mendocino AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "Conejo Simi Moorpark AOR",
    "Simi Valley-Moorpark AOR, Inc.",
    "High Desert AOR",
    "Simi 0420 - Old Keyboxes",
    "Meritage HB Coop 2",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Silicon Valley AOR OLD",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "Greater Palm Springs - CA",
  ],
  "Inland Valleys AOR - CA": [
    "Coastal Mendocino AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "Conejo Simi Moorpark AOR",
    "Simi Valley-Moorpark AOR, Inc.",
    "High Desert AOR",
    "Desert Communities-Old",
    "Simi 0420 - Old Keyboxes",
    "Meritage HB Coop 2",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Silicon Valley AOR OLD",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "Greater Palm Springs - CA",
  ],
  "Jasper Area Board of Realtors": ["Lufkin MLS"],
  "Johnson County AOR": [
    "Greater Tyler AOR",
    "Waco Association of Realtors",
    "Texoma 2",
    "Heartland AOR",
  ],
  "Joshua Tree Gateway AOR": [
    "Coastal Mendocino AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "High Desert AOR",
    "Desert Communities-Old",
    "Meritage HB Coop 2",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Silicon Valley AOR OLD",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Santa Clara County AOR",
    "Burbank Association of Realtors",
    "CLAW-Combined LA Westside MLS",
    "Greater Palm Springs - CA",
  ],
  "Kansas City Regional AOR": [
    "West Central AOR",
    "Five County Board of REALTORS",
    "Central Missouri Board of Rltrs",
    "Ozarks Board of Realtors",
  ],
  "Kingsville Area AOR": ["Corpus Christi AOR"],
  "Knox County BOR": ["Southwest Indiana AOR"],
  "Knox County BOR - OH": [
    "Licking County Board of Realtors",
    "Columbus Realtors - OH",
  ],
  "Kosciusko Board of Realtors": [
    "Bloomington MLS",
    "South Bend Area Realtors Inc",
    "Lafayette Regional BOR",
    "Northeastern Indiana AOR",
    "North Central Indiana AOR",
    "Indiana Regional MLS",
    "Elkhart County Board of Realtors",
  ],
  "Lafayette Regional BOR": [
    "Bloomington MLS",
    "South Bend Area Realtors Inc",
    "Kosciusko Board of Realtors",
    "Northeastern Indiana AOR",
    "North Central Indiana AOR",
    "Indiana Regional MLS",
    "Elkhart County Board of Realtors",
  ],
  "Laguna Board of Realtors": [
    "Coastal Mendocino AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "Conejo Simi Moorpark AOR",
    "Simi Valley-Moorpark AOR, Inc.",
    "High Desert AOR",
    "Simi 0420 - Old Keyboxes",
    "Meritage HB Coop 2",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Silicon Valley AOR OLD",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "Greater Palm Springs - CA",
  ],
  "Lake Cities AOR": [
    "Greater Tyler AOR",
    "Waco Association of Realtors",
    "Texoma 2",
  ],
  "Lake of the Ozarks - MO": ["Lake of the Ozarks - MO OLD"],
  "Lake of the Ozarks - MO OLD": ["Bagnell Dam AOR", "Lake of the Ozarks - MO"],
  "Lake Superior Area Realtors": [
    "SE Minnesota Assoc of Rltrs",
    "Minneapolis AOR and St Paul AOR",
    "Western Wisconsin Realtors Assoc",
    "Realtor Assoc of So Minnesota",
    "St Cloud Area AOR",
  ],
  "Lawton Board of Realtors": [
    "OKCMAR - OK",
    "Norman BOR - OK",
    "Altus Association of REALTORS",
  ],
  "Lexington Bluegrass AOR": [
    "Gr Louisville Assoc of Realtors",
    "Northern Kentucky MLS",
  ],
  "Licking County Board of Realtors": [
    "Licking County BOR - OLD",
    "Knox County BOR - OH",
  ],
  "Licking County BOR - OLD": ["Licking County Board of Realtors"],
  "Longview Area AOR": ["Greater Tyler AOR"],
  "Lufkin MLS": ["Nacogdoches County BOR", "Jasper Area Board of Realtors"],
  "Madera County AOR": [
    "Yosemite Gateway AOR",
    "Silicon Valley Assoc of Realtors",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
  ],
  "Marin Association of Realtors": ["BAREIS"],
  "Marshall County BOR": [
    "Greater Alabama MLS",
    "Etowah/Cherokee County AOR",
    "Calhoun Cty Area BOR",
  ],
  "Martinsville-Henry-Patrick Co": ["Dan River Region AOR"],
  "Merced County AOR": [
    "Yosemite Gateway AOR",
    "Coastal Mendocino AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "High Desert AOR",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
    "Palos Verdes Peninsula AOR",
    "Inglewood Board of Realtors",
    "South Bay AOR",
    "Pasadena-Foothills AOR",
    "Glendale Association of Realtors",
    "Arcadia Association of Realtors",
    "Montebello Assoc of Realtors",
    "West San Gabriel Valley Realtors",
    "Tri-Counties AOR",
    "Citrus Valley AOR",
    "Inland Valleys AOR - CA",
    "The Inland Gateway a dba - EVAR",
    "SW Riverside Assoc of Rltrs",
    "The Inland Gateway a dba - TIGAR",
    "Orange County Realtors - CA",
    "Laguna Board of Realtors",
    "Downey Association of Realtors",
    "Rancho Southeast AOR",
    "Pac West AOR",
    "Orange Coast AOR",
    "Joshua Tree Gateway AOR",
    "North San Diego Co Assn of Rltrs",
    "Pacific Southwest AOR",
    "Southland Reg. AOR",
  ],
  "Meritage HB Coop 2": [
    "ARMLS-Arizona Regional MLS",
    "MLS of So AZ",
    "Granbury Association of Realtors",
    "Palos Verdes Peninsula AOR",
    "Inglewood Board of Realtors",
    "South Bay AOR",
    "Pasadena-Foothills AOR",
    "Glendale Association of Realtors",
    "Arcadia Association of Realtors",
    "Montebello Assoc of Realtors",
    "West San Gabriel Valley Realtors",
    "Tri-Counties AOR",
    "Citrus Valley AOR",
    "Inland Valleys AOR - CA",
    "The Inland Gateway a dba - EVAR",
    "SW Riverside Assoc of Rltrs",
    "Orange County Realtors - CA",
    "Laguna Board of Realtors",
    "Downey Association of Realtors",
    "Rancho Southeast AOR",
    "Pac West AOR",
    "Orange Coast AOR",
    "Joshua Tree Gateway AOR",
    "North San Diego Co Assn of Rltrs",
    "Pacific Southwest AOR",
  ],
  "Metrolist Services": ["Nevada County AOR", "Sutter Yuba AOR"],
  "MetroTex Key Services": [
    "Greater Tyler AOR",
    "Waco Association of Realtors",
    "Texoma 2",
    "Heartland AOR",
  ],
  "Mid Illinois RA - IL": [
    "Central Illinois BOR, Inc - IL",
    "Champaign County",
  ],
  "Mineral Area Board of Rltrs-OLD": [
    "St Louis Realtors Association",
    "Franklin County BOR",
    "St Charles County AOR",
    "East Central Board of Realtors",
    "Southern Gateway AOR - MO",
    "Mineral Area BOR",
  ],
  "Mineral Area BOR": [
    "MLS of Springfield Realtors",
    "Mineral Area Board of Rltrs-OLD",
    "South Central Board of REALTORS",
  ],
  "Minneapolis AOR and St Paul AOR": [
    "Gr Alexandria Assoc of Rltrs",
    "Fargo Moorhead Area AOR",
    "SE Minnesota Assoc of Rltrs",
    "Realtor Assoc of So Minnesota",
    "St Cloud Area AOR",
    "Lake Superior Area Realtors",
    "Detroit Lakes Area BOR dba LCAR",
    "Northwest Minnesota AOR",
  ],
  "MLS of So AZ": ["Meritage HB Coop 2"],
  "MLS of Springfield Realtors": [
    "Mineral Area BOR",
    "Tri-Lakes MLS, Inc",
    "Pulaski County Board of Realtors",
    "West Central AOR",
    "Ozarks Board of Realtors",
    "Ozark Trail Board of Realtors",
  ],
  "MLS United, LLC - MS": ["Central Mississippi MLS"],
  "Montebello Assoc of Realtors": [
    "Coastal Mendocino AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "Conejo Simi Moorpark AOR",
    "Simi Valley-Moorpark AOR, Inc.",
    "High Desert AOR",
    "Simi 0420 - Old Keyboxes",
    "Meritage HB Coop 2",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Silicon Valley AOR OLD",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "Greater Palm Springs - CA",
  ],
  "Monterey County AOR": [
    "Coastal Mendocino AOR",
    "Tuolumne County AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "High Desert AOR",
    "Madera County AOR",
    "Palos Verdes Peninsula AOR",
    "Inglewood Board of Realtors",
    "South Bay AOR",
    "Pasadena-Foothills AOR",
    "Glendale Association of Realtors",
    "Arcadia Association of Realtors",
    "Montebello Assoc of Realtors",
    "West San Gabriel Valley Realtors",
    "Tri-Counties AOR",
    "Citrus Valley AOR",
    "Inland Valleys AOR - CA",
    "The Inland Gateway a dba - EVAR",
    "SW Riverside Assoc of Rltrs",
    "The Inland Gateway a dba - TIGAR",
    "Orange County Realtors - CA",
    "Laguna Board of Realtors",
    "Downey Association of Realtors",
    "Rancho Southeast AOR",
    "Pac West AOR",
    "Orange Coast AOR",
    "Joshua Tree Gateway AOR",
    "North San Diego Co Assn of Rltrs",
    "Pacific Southwest AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "Simi CD59 (Old Keyboxes)",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "California Desert AOR",
  ],
  "Morgan County AOR": [
    "Greater Alabama MLS",
    "Etowah/Cherokee County AOR",
    "Calhoun Cty Area BOR",
  ],
  "Mountain Communities": [
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "Conejo Simi Moorpark AOR",
    "Simi Valley-Moorpark AOR, Inc.",
    "Simi 0420 - Old Keyboxes",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
    "Palos Verdes Peninsula AOR",
    "Inglewood Board of Realtors",
    "South Bay AOR",
    "Pasadena-Foothills AOR",
    "Glendale Association of Realtors",
    "Montebello Assoc of Realtors",
    "West San Gabriel Valley Realtors",
    "Tri-Counties AOR",
    "Citrus Valley AOR",
    "Inland Valleys AOR - CA",
    "The Inland Gateway a dba - EVAR",
    "SW Riverside Assoc of Rltrs",
    "Orange County Realtors - CA",
    "Laguna Board of Realtors",
    "Downey Association of Realtors",
    "Rancho Southeast AOR",
    "Pac West AOR",
    "Orange Coast AOR",
    "North San Diego Co Assn of Rltrs",
    "Pacific Southwest AOR",
  ],
  "Mountain Resort Communities": ["Mountain Resort Communities- RIM"],
  "Mountain Resort Communities- RIM": ["Mountain Resort Communities"],
  "Murray Calloway County BOR": [
    "Paducah BOR-MG",
    "Paducah BOR",
    "Paducah BOR- KBL",
  ],
  "N Texas RE Technical Services": [
    "Greater Tyler AOR",
    "Waco Association of Realtors",
    "Texoma 2",
    "Heartland AOR",
  ],
  "Nacogdoches County BOR": ["Lufkin MLS"],
  "Natchitoches Board of Realtors": ["Central Louisiana BOR"],
  "Nevada County AOR": ["Metrolist Services"],
  "NORES-Northeast Oklahoma RE Svc": [
    "Southeastern Oklahoma AOR",
    "Ada Board of Realtors",
  ],
  "Norman BOR - OK": [
    "OKCMAR - OK",
    "Ada Board of Realtors",
    "Lawton Board of Realtors",
    "Shawnee Board of Realtors",
    "Altus Association of REALTORS",
  ],
  "North Central Indiana AOR": [
    "Gr NW Indiana AOR and Laporte",
    "Bloomington MLS",
    "South Bend Area Realtors Inc",
    "Lafayette Regional BOR",
    "Kosciusko Board of Realtors",
    "Indiana Regional MLS",
    "Elkhart County Board of Realtors",
  ],
  "North San Diego Co Assn of Rltrs": [
    "Coastal Mendocino AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "Conejo Simi Moorpark AOR",
    "Simi Valley-Moorpark AOR, Inc.",
    "High Desert AOR",
    "Simi 0420 - Old Keyboxes",
    "Meritage HB Coop 2",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Silicon Valley AOR OLD",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
    "Southland Reg. AOR",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "California Desert AOR",
  ],
  "Northeastern Indiana AOR": [
    "Bloomington MLS",
    "South Bend Area Realtors Inc",
    "Lafayette Regional BOR",
    "Kosciusko Board of Realtors",
    "Indiana Regional MLS",
    "Elkhart County Board of Realtors",
  ],
  "Northern Kentucky MLS": ["Lexington Bluegrass AOR"],
  "Northshore Area BOR": [
    "Gr Baton Rouge Assoc of Rltrs",
    "SW Louisiana Assoc of Rltrs",
    "Bayou Board of Realtors",
    "Gulf South REIN",
  ],
  "Northwest Minnesota AOR": [
    "Fargo Moorhead Area AOR",
    "SE Minnesota Assoc of Rltrs",
    "Minneapolis AOR and St Paul AOR",
    "St Cloud Area AOR",
    "Detroit Lakes Area BOR dba LCAR",
  ],
  "Oakland Association of Realtors": ["Silicon Valley Assoc of Realtors"],
  "Odessa Board of REALTORS": [
    "Permian Basin Board of REALTORS",
    "Snyder Board of REALTORS",
  ],
  "OKCMAR - OK": [
    "Norman BOR - OK",
    "Ada Board of Realtors",
    "Lawton Board of Realtors",
    "Shawnee Board of Realtors",
    "Altus Association of REALTORS",
    "Southern Oklahoma BOR",
  ],
  "OLD BAREIS": ["BAREIS"],
  "Orange Coast AOR": [
    "Coastal Mendocino AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "Conejo Simi Moorpark AOR",
    "Simi Valley-Moorpark AOR, Inc.",
    "High Desert AOR",
    "Simi 0420 - Old Keyboxes",
    "Meritage HB Coop 2",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Silicon Valley AOR OLD",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "Greater Palm Springs - CA",
    "Orange Coast Newport Keyboxes",
  ],
  "Orange Coast Newport Keyboxes": ["Orange Coast AOR"],
  "Orange County Realtors - CA": [
    "Coastal Mendocino AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "Conejo Simi Moorpark AOR",
    "Simi Valley-Moorpark AOR, Inc.",
    "High Desert AOR",
    "Simi 0420 - Old Keyboxes",
    "Meritage HB Coop 2",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Silicon Valley AOR OLD",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "Greater Palm Springs - CA",
  ],
  "Ozark Trail Board of Realtors": [
    "MLS of Springfield Realtors",
    "Tri-Lakes MLS, Inc",
    "Ozarks Board of Realtors",
  ],
  "Ozarks Board of Realtors": [
    "MLS of Springfield Realtors",
    "Tri-Lakes MLS, Inc",
    "Kansas City Regional AOR",
    "West Central AOR",
    "Ozark Trail Board of Realtors",
  ],
  "Pac West AOR": [
    "Coastal Mendocino AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "Conejo Simi Moorpark AOR",
    "Simi Valley-Moorpark AOR, Inc.",
    "High Desert AOR",
    "Simi 0420 - Old Keyboxes",
    "Meritage HB Coop 2",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Silicon Valley AOR OLD",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "Greater Palm Springs - CA",
  ],
  "Pacific Southwest AOR": [
    "Coastal Mendocino AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "Conejo Simi Moorpark AOR",
    "Simi Valley-Moorpark AOR, Inc.",
    "High Desert AOR",
    "Simi 0420 - Old Keyboxes",
    "Meritage HB Coop 2",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Silicon Valley AOR OLD",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "Greater Palm Springs - CA",
  ],
  "Paducah BOR": ["Paducah BOR- KBL", "Murray Calloway County BOR"],
  "Paducah BOR- KBL": [
    "Paducah BOR-MG",
    "Paducah BOR",
    "Murray Calloway County BOR",
  ],
  "Paducah BOR-MG": ["Paducah BOR- KBL", "Murray Calloway County BOR"],
  "Pajaro Valley AOR": ["Silicon Valley Assoc of Realtors"],
  "Palos Verdes Peninsula AOR": [
    "Coastal Mendocino AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "Conejo Simi Moorpark AOR",
    "Simi Valley-Moorpark AOR, Inc.",
    "High Desert AOR",
    "Simi 0420 - Old Keyboxes",
    "Meritage HB Coop 2",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Silicon Valley AOR OLD",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "Greater Palm Springs - CA",
  ],
  "Pasadena-Foothills AOR": [
    "Coastal Mendocino AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "Conejo Simi Moorpark AOR",
    "Simi Valley-Moorpark AOR, Inc.",
    "High Desert AOR",
    "Simi Valley Coops",
    "Meritage HB Coop 2",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Silicon Valley AOR OLD",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "California Desert AOR",
    "Greater Palm Springs - CA",
  ],
  "Permian Basin Board of REALTORS": [
    "Odessa Board of REALTORS",
    "Snyder Board of REALTORS",
  ],
  "Pike County Board of REALTORS": ["Wiregrass MLS"],
  "Pulaski County Board of Realtors": [
    "MLS of Springfield Realtors",
    "South Central Board of REALTORS",
  ],
  "Rancho Southeast AOR": [
    "Coastal Mendocino AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "Conejo Simi Moorpark AOR",
    "Simi Valley-Moorpark AOR, Inc.",
    "High Desert AOR",
    "Simi 0420 - Old Keyboxes",
    "Meritage HB Coop 2",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Silicon Valley AOR OLD",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "Greater Palm Springs - CA",
  ],
  "Real Estate Information Services": ["South Central Kentucky AOR"],
  "Realtor Assoc of So Minnesota": [
    "Fargo Moorhead Area AOR",
    "SE Minnesota Assoc of Rltrs",
    "Minneapolis AOR and St Paul AOR",
    "Western Wisconsin Realtors Assoc",
    "St Cloud Area AOR",
    "Lake Superior Area Realtors",
  ],
  "Realtor Association of Acadiana": [
    "Gr Baton Rouge Assoc of Rltrs",
    "Bayou Board of Realtors",
    "Gulf South REIN",
  ],
  "Rockbridge Highlands Realtors": [
    "Charlottesville Area AOR",
    "Greater Augusta AOR",
  ],
  "San Antonio Board of Realtors": [
    "Victoria Area AOR",
    "Unlock MLS a dba of ACTRIS",
    "Four Rivers AOR",
    "Houston Association of Realtors",
  ],
  "San Benito County AOR": [
    "Coastal Mendocino AOR",
    "Tuolumne County AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "High Desert AOR",
    "Madera County AOR",
    "Palos Verdes Peninsula AOR",
    "Inglewood Board of Realtors",
    "South Bay AOR",
    "Pasadena-Foothills AOR",
    "Glendale Association of Realtors",
    "Arcadia Association of Realtors",
    "Montebello Assoc of Realtors",
    "West San Gabriel Valley Realtors",
    "Tri-Counties AOR",
    "Citrus Valley AOR",
    "Inland Valleys AOR - CA",
    "The Inland Gateway a dba - EVAR",
    "SW Riverside Assoc of Rltrs",
    "The Inland Gateway a dba - TIGAR",
    "Orange County Realtors - CA",
    "Laguna Board of Realtors",
    "Downey Association of Realtors",
    "Rancho Southeast AOR",
    "Pac West AOR",
    "Orange Coast AOR",
    "Joshua Tree Gateway AOR",
    "North San Diego Co Assn of Rltrs",
    "Pacific Southwest AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "Simi CD59 (Old Keyboxes)",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "California Desert AOR",
  ],
  "San Francisco AOR": [
    "Coastal Mendocino AOR",
    "Tuolumne County AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "High Desert AOR",
    "Madera County AOR",
    "Palos Verdes Peninsula AOR",
    "Inglewood Board of Realtors",
    "South Bay AOR",
    "Pasadena-Foothills AOR",
    "Glendale Association of Realtors",
    "Arcadia Association of Realtors",
    "Montebello Assoc of Realtors",
    "West San Gabriel Valley Realtors",
    "Tri-Counties AOR",
    "Citrus Valley AOR",
    "Inland Valleys AOR - CA",
    "The Inland Gateway a dba - EVAR",
    "SW Riverside Assoc of Rltrs",
    "The Inland Gateway a dba - TIGAR",
    "Orange County Realtors - CA",
    "Laguna Board of Realtors",
    "Downey Association of Realtors",
    "Rancho Southeast AOR",
    "Pac West AOR",
    "Orange Coast AOR",
    "Joshua Tree Gateway AOR",
    "North San Diego Co Assn of Rltrs",
    "Pacific Southwest AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "Simi CD59 (Old Keyboxes)",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "California Desert AOR",
  ],
  "San Mateo County AOR": [
    "Coastal Mendocino AOR",
    "Tuolumne County AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "High Desert AOR",
    "Madera County AOR",
    "Palos Verdes Peninsula AOR",
    "Inglewood Board of Realtors",
    "South Bay AOR",
    "Pasadena-Foothills AOR",
    "Glendale Association of Realtors",
    "Arcadia Association of Realtors",
    "Montebello Assoc of Realtors",
    "West San Gabriel Valley Realtors",
    "Tri-Counties AOR",
    "Citrus Valley AOR",
    "Inland Valleys AOR - CA",
    "The Inland Gateway a dba - EVAR",
    "SW Riverside Assoc of Rltrs",
    "The Inland Gateway a dba - TIGAR",
    "Orange County Realtors - CA",
    "Laguna Board of Realtors",
    "Downey Association of Realtors",
    "Rancho Southeast AOR",
    "Pac West AOR",
    "Orange Coast AOR",
    "Joshua Tree Gateway AOR",
    "North San Diego Co Assn of Rltrs",
    "Pacific Southwest AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "Simi CD59 (Old Keyboxes)",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "California Desert AOR",
  ],
  "Santa Clara County AOR": [
    "Coastal Mendocino AOR",
    "Tuolumne County AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "High Desert AOR",
    "Madera County AOR",
    "Palos Verdes Peninsula AOR",
    "Inglewood Board of Realtors",
    "South Bay AOR",
    "Pasadena-Foothills AOR",
    "Glendale Association of Realtors",
    "Arcadia Association of Realtors",
    "Montebello Assoc of Realtors",
    "West San Gabriel Valley Realtors",
    "Tri-Counties AOR",
    "Citrus Valley AOR",
    "Inland Valleys AOR - CA",
    "The Inland Gateway a dba - EVAR",
    "SW Riverside Assoc of Rltrs",
    "The Inland Gateway a dba - TIGAR",
    "Orange County Realtors - CA",
    "Laguna Board of Realtors",
    "Downey Association of Realtors",
    "Rancho Southeast AOR",
    "Pac West AOR",
    "Orange Coast AOR",
    "Joshua Tree Gateway AOR",
    "North San Diego Co Assn of Rltrs",
    "Pacific Southwest AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "Simi CD59 (Old Keyboxes)",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "California Desert AOR",
  ],
  "Santa Cruz County AOR": [
    "Coastal Mendocino AOR",
    "Tuolumne County AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "High Desert AOR",
    "Madera County AOR",
    "Palos Verdes Peninsula AOR",
    "Inglewood Board of Realtors",
    "South Bay AOR",
    "Pasadena-Foothills AOR",
    "Glendale Association of Realtors",
    "Arcadia Association of Realtors",
    "Montebello Assoc of Realtors",
    "West San Gabriel Valley Realtors",
    "Tri-Counties AOR",
    "Citrus Valley AOR",
    "Inland Valleys AOR - CA",
    "The Inland Gateway a dba - EVAR",
    "SW Riverside Assoc of Rltrs",
    "The Inland Gateway a dba - TIGAR",
    "Orange County Realtors - CA",
    "Laguna Board of Realtors",
    "Downey Association of Realtors",
    "Rancho Southeast AOR",
    "Pac West AOR",
    "Orange Coast AOR",
    "Joshua Tree Gateway AOR",
    "North San Diego Co Assn of Rltrs",
    "Pacific Southwest AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "Simi CD59 (Old Keyboxes)",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
  ],
  "Santa Cruz County MLS": [
    "MLS of So AZ",
    "Southeast Arizona AOR",
    "Green Valley/Sahuarita AOR",
    "Douglas Association of Realtors",
    "California Desert AOR",
  ],
  "SE Minnesota Assoc of Rltrs": [
    "Gr Alexandria Assoc of Rltrs",
    "Minneapolis AOR and St Paul AOR",
    "Realtor Assoc of So Minnesota",
    "St Cloud Area AOR",
    "Lake Superior Area Realtors",
    "Detroit Lakes Area BOR dba LCAR",
    "Northwest Minnesota AOR",
  ],
  "Sedona-Verde Valley AOR": ["ARMLS-Arizona Regional MLS"],
  "Shawnee Board of Realtors": [
    "OKCMAR - OK",
    "Norman BOR - OK",
    "Ada Board of Realtors",
  ],
  "Silicon Valley AOR OLD": [
    "Tuolumne County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "High Desert AOR",
    "Palos Verdes Peninsula AOR",
    "Inglewood Board of Realtors",
    "South Bay AOR",
    "Pasadena-Foothills AOR",
    "Glendale Association of Realtors",
    "Arcadia Association of Realtors",
    "Montebello Assoc of Realtors",
    "West San Gabriel Valley Realtors",
    "Tri-Counties AOR",
    "Citrus Valley AOR",
    "Inland Valleys AOR - CA",
    "The Inland Gateway a dba - EVAR",
    "SW Riverside Assoc of Rltrs",
    "The Inland Gateway a dba - TIGAR",
    "Orange County Realtors - CA",
    "Laguna Board of Realtors",
    "Rancho Southeast AOR",
    "Pac West AOR",
    "Orange Coast AOR",
    "Joshua Tree Gateway AOR",
    "North San Diego Co Assn of Rltrs",
    "Pacific Southwest AOR",
    "Burbank Association of Realtors",
  ],
  "Silicon Valley Assoc of Realtors": [
    "Coastal Mendocino AOR",
    "Tuolumne County AOR",
    "Merced County AOR",
    "Ventura County Coastal AOR",
    "High Desert AOR",
    "Monterey County AOR",
    "Pajaro Valley AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Silicon Valley AOR OLD",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Oakland Association of Realtors",
    "West Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
    "Central Valley AOR",
    "Madera County AOR",
    "Palos Verdes Peninsula AOR",
    "Inglewood Board of Realtors",
    "South Bay AOR",
    "Pasadena-Foothills AOR",
    "Glendale Association of Realtors",
    "Arcadia Association of Realtors",
    "Montebello Assoc of Realtors",
    "West San Gabriel Valley Realtors",
    "Tri-Counties AOR",
    "Citrus Valley AOR",
    "Inland Valleys AOR - CA",
    "The Inland Gateway a dba - EVAR",
    "SW Riverside Assoc of Rltrs",
    "The Inland Gateway a dba - TIGAR",
    "Orange County Realtors - CA",
    "Laguna Board of Realtors",
    "Downey Association of Realtors",
    "Rancho Southeast AOR",
    "Pac West AOR",
    "Orange Coast AOR",
    "Joshua Tree Gateway AOR",
    "North San Diego Co Assn of Rltrs",
    "Pacific Southwest AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "Simi CD59 (Old Keyboxes)",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "California Desert AOR",
  ],
  "Simi 0420 - Old Keyboxes": [
    "Ventura County Coastal AOR",
    "Conejo Simi Moorpark AOR",
    "Simi Valley-Moorpark AOR, Inc.",
    "Palos Verdes Peninsula AOR",
    "Inglewood Board of Realtors",
    "South Bay AOR",
    "Pasadena-Foothills AOR",
    "Glendale Association of Realtors",
    "Arcadia Association of Realtors",
    "Montebello Assoc of Realtors",
    "West San Gabriel Valley Realtors",
    "Tri-Counties AOR",
    "Citrus Valley AOR",
    "Inland Valleys AOR - CA",
    "The Inland Gateway a dba - EVAR",
    "SW Riverside Assoc of Rltrs",
    "The Inland Gateway a dba - TIGAR",
    "Orange County Realtors - CA",
    "Laguna Board of Realtors",
    "Downey Association of Realtors",
    "Rancho Southeast AOR",
    "Pac West AOR",
    "Orange Coast AOR",
    "North San Diego Co Assn of Rltrs",
    "Pacific Southwest AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "Greater Palm Springs - CA",
  ],
  "Simi CD59 (Old Keyboxes)": [
    "Silicon Valley Assoc of Realtors",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
  ],
  "Simi Valley Coops": ["Pasadena-Foothills AOR"],
  "Simi Valley-Moorpark AOR, Inc.": [
    "Simi 0420 - Old Keyboxes",
    "Palos Verdes Peninsula AOR",
    "Inglewood Board of Realtors",
    "South Bay AOR",
    "Pasadena-Foothills AOR",
    "Glendale Association of Realtors",
    "Arcadia Association of Realtors",
    "Montebello Assoc of Realtors",
    "West San Gabriel Valley Realtors",
    "Tri-Counties AOR",
    "Citrus Valley AOR",
    "Inland Valleys AOR - CA",
    "The Inland Gateway a dba - EVAR",
    "SW Riverside Assoc of Rltrs",
    "The Inland Gateway a dba - TIGAR",
    "Orange County Realtors - CA",
    "Laguna Board of Realtors",
    "Downey Association of Realtors",
    "Rancho Southeast AOR",
    "Pac West AOR",
    "Orange Coast AOR",
    "North San Diego Co Assn of Rltrs",
    "Pacific Southwest AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "California Desert AOR",
    "Greater Palm Springs - CA",
  ],
  "Snyder Board of REALTORS": [
    "Permian Basin Board of REALTORS",
    "Odessa Board of REALTORS",
  ],
  "South Bay AOR": [
    "Coastal Mendocino AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "Conejo Simi Moorpark AOR",
    "Simi Valley-Moorpark AOR, Inc.",
    "High Desert AOR",
    "Simi 0420 - Old Keyboxes",
    "Meritage HB Coop 2",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Silicon Valley AOR OLD",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "Greater Palm Springs - CA",
  ],
  "South Bend Area Realtors Inc": [
    "Gr NW Indiana AOR and Laporte",
    "Bloomington MLS",
    "Lafayette Regional BOR",
    "Kosciusko Board of Realtors",
    "Northeastern Indiana AOR",
    "North Central Indiana AOR",
    "Indiana Regional MLS",
    "Elkhart County Board of Realtors",
  ],
  "South Central Board of REALTORS": [
    "St Louis Realtors Association",
    "Franklin County BOR",
    "St Charles County AOR",
    "East Central Board of Realtors",
    "Southern Gateway AOR - MO",
    "Mineral Area BOR",
    "Pulaski County Board of Realtors",
  ],
  "South Central Kentucky AOR": ["Real Estate Information Services"],
  "South Central Wisconsin MLS": [
    "Greater La Crosse Area MLS Corp",
    "Central Wisconsin BOR",
  ],
  "Southeast Alabama AOR - AL": [
    "Covington Board of REALTORS",
    "Eufaula Board of Realtors",
    "Wiregrass MLS",
  ],
  "Southeast Arizona AOR": [
    "ARMLS-Arizona Regional MLS",
    "Green Valley/Sahuarita AOR",
    "Santa Cruz County MLS",
    "Douglas Association of Realtors",
  ],
  "Southeastern Oklahoma AOR": ["NORES-Northeast Oklahoma RE Svc"],
  "Southern Gateway AOR - MO": [
    "Mineral Area Board of Rltrs-OLD",
    "South Central Board of REALTORS",
  ],
  "Southern Oklahoma BOR": ["OKCMAR - OK", "Ada Board of Realtors"],
  "Southland Reg. AOR": [
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "Conejo Simi Moorpark AOR",
    "Conejo Valley Coops",
    "Simi Valley-Moorpark AOR, Inc.",
    "High Desert AOR",
    "Simi 0420 - Old Keyboxes",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
    "Palos Verdes Peninsula AOR",
    "Inglewood Board of Realtors",
    "South Bay AOR",
    "Pasadena-Foothills AOR",
    "Glendale Association of Realtors",
    "Arcadia Association of Realtors",
    "Montebello Assoc of Realtors",
    "West San Gabriel Valley Realtors",
    "Tri-Counties AOR",
    "Citrus Valley AOR",
    "Inland Valleys AOR - CA",
    "The Inland Gateway a dba - EVAR",
    "SW Riverside Assoc of Rltrs",
    "The Inland Gateway a dba - TIGAR",
    "Orange County Realtors - CA",
    "Laguna Board of Realtors",
    "Downey Association of Realtors",
    "Rancho Southeast AOR",
    "Pac West AOR",
    "Orange Coast AOR",
    "North San Diego Co Assn of Rltrs",
    "Pacific Southwest AOR",
    "California Desert AOR",
    "Greater Palm Springs - CA",
  ],
  "Southwest Indiana AOR": ["Knox County BOR"],
  "St Charles County AOR": [
    "Mineral Area Board of Rltrs-OLD",
    "South Central Board of REALTORS",
  ],
  "St Cloud Area AOR": [
    "Gr Alexandria Assoc of Rltrs",
    "Fargo Moorhead Area AOR",
    "SE Minnesota Assoc of Rltrs",
    "Minneapolis AOR and St Paul AOR",
    "Western Wisconsin Realtors Assoc",
    "Realtor Assoc of So Minnesota",
    "Lake Superior Area Realtors",
    "Detroit Lakes Area BOR dba LCAR",
    "Northwest Minnesota AOR",
  ],
  "St Louis Realtors Association": [
    "Mineral Area Board of Rltrs-OLD",
    "South Central Board of REALTORS",
  ],
  "Stephenville AOR": [
    "Greater Tyler AOR",
    "Waco Association of Realtors",
    "Texoma 2",
    "Heartland AOR",
  ],
  "Sutter Yuba AOR": ["Metrolist Services"],
  "SW Illinois BOR": ["Central Illinois BOR, Inc - IL"],
  "SW Iowa Assoc of Realtors": ["Great Plains MLS Omaha"],
  "SW Louisiana Assoc of Rltrs": ["Northshore Area BOR"],
  "SW Riverside Assoc of Rltrs": [
    "Coastal Mendocino AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "Conejo Simi Moorpark AOR",
    "Simi Valley-Moorpark AOR, Inc.",
    "High Desert AOR",
    "Simi 0420 - Old Keyboxes",
    "Meritage HB Coop 2",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Silicon Valley AOR OLD",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "Greater Palm Springs - CA",
  ],
  "Tall Pines AOR - TX": ["Houston Association of Realtors"],
  "Temple Belton BOR": [
    "Victoria Area AOR",
    "Four Rivers AOR",
    "Fort Hood Area AOR",
    "Williamson County AOR",
  ],
  "Texoma 2": [
    "Gr Fort Worth Assoc of Rltrs",
    "Gr Denton-Wise Assoc of Rltrs",
    "Arlington Board of Realtors",
    "Granbury Association of Realtors",
    "Greater Metro West AOR, a dba",
    "Johnson County AOR",
    "Greater Texoma AOR",
    "Lake Cities AOR",
    "MetroTex Key Services",
    "Collin County Area Realtors, Inc",
    "N Texas RE Technical Services",
    "Stephenville AOR",
  ],
  "The Inland Gateway a dba - EVAR": [
    "Coastal Mendocino AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "Conejo Simi Moorpark AOR",
    "Simi Valley-Moorpark AOR, Inc.",
    "High Desert AOR",
    "Desert Communities-Old",
    "Simi 0420 - Old Keyboxes",
    "Meritage HB Coop 2",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Silicon Valley AOR OLD",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "Greater Palm Springs - CA",
  ],
  "The Inland Gateway a dba - TIGAR": [
    "Coastal Mendocino AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "Conejo Simi Moorpark AOR",
    "Simi Valley-Moorpark AOR, Inc.",
    "High Desert AOR",
    "Simi 0420 - Old Keyboxes",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Silicon Valley AOR OLD",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "CLAW-Combined LA Westside MLS",
    "Greater Palm Springs - CA",
  ],
  "Tri-Counties AOR": [
    "Coastal Mendocino AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "Conejo Simi Moorpark AOR",
    "Simi Valley-Moorpark AOR, Inc.",
    "High Desert AOR",
    "Simi 0420 - Old Keyboxes",
    "Meritage HB Coop 2",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Silicon Valley AOR OLD",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "Greater Palm Springs - CA",
  ],
  "Tri-Lakes MLS, Inc": [
    "MLS of Springfield Realtors",
    "Ozarks Board of Realtors",
    "Ozark Trail Board of Realtors",
  ],
  "Tuolumne County AOR": [
    "Silicon Valley Assoc of Realtors",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Silicon Valley AOR OLD",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
  ],
  "Unlock MLS a dba of ACTRIS": [
    "Highland Lakes AOR",
    "San Antonio Board of Realtors",
    "Four Rivers AOR",
    "Houston Association of Realtors",
  ],
  "Ventura County Coastal AOR": [
    "Coastal Mendocino AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "High Desert AOR",
    "Simi 0420 - Old Keyboxes",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Silicon Valley AOR OLD",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
    "Palos Verdes Peninsula AOR",
    "Inglewood Board of Realtors",
    "South Bay AOR",
    "Pasadena-Foothills AOR",
    "Glendale Association of Realtors",
    "Arcadia Association of Realtors",
    "Montebello Assoc of Realtors",
    "West San Gabriel Valley Realtors",
    "Tri-Counties AOR",
    "Citrus Valley AOR",
    "Inland Valleys AOR - CA",
    "The Inland Gateway a dba - EVAR",
    "SW Riverside Assoc of Rltrs",
    "The Inland Gateway a dba - TIGAR",
    "Orange County Realtors - CA",
    "Laguna Board of Realtors",
    "Downey Association of Realtors",
    "Rancho Southeast AOR",
    "Pac West AOR",
    "Orange Coast AOR",
    "North San Diego Co Assn of Rltrs",
    "Pacific Southwest AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "California Desert AOR",
    "Greater Palm Springs - CA",
  ],
  "Victoria Area AOR": [
    "San Antonio Board of Realtors",
    "Four Rivers AOR",
    "Fort Hood Area AOR",
    "Williamson County AOR",
    "Temple Belton BOR",
  ],
  "Waco Association of Realtors": [
    "Greater Tyler AOR",
    "Gr Fort Worth Assoc of Rltrs",
    "Gr Denton-Wise Assoc of Rltrs",
    "Arlington Board of Realtors",
    "Granbury Association of Realtors",
    "Greater Metro West AOR, a dba",
    "Johnson County AOR",
    "Greater Texoma AOR",
    "Lake Cities AOR",
    "MetroTex Key Services",
    "Collin County Area Realtors, Inc",
    "N Texas RE Technical Services",
    "Stephenville AOR",
  ],
  "West Contra Costa AOR": ["Silicon Valley Assoc of Realtors"],
  "West San Gabriel Valley Realtors": [
    "Coastal Mendocino AOR",
    "Merced County AOR",
    "Silicon Valley Assoc of Realtors",
    "Ventura County Coastal AOR",
    "Conejo Simi Moorpark AOR",
    "Simi Valley-Moorpark AOR, Inc.",
    "High Desert AOR",
    "Simi 0420 - Old Keyboxes",
    "Meritage HB Coop 2",
    "Monterey County AOR",
    "Santa Cruz County AOR",
    "San Mateo County AOR",
    "San Benito County AOR",
    "San Francisco AOR",
    "Silicon Valley AOR OLD",
    "Bay East Association of Realtors",
    "Contra Costa AOR",
    "Delta Association of Realtors",
    "Bridge Association of Rltrs - CA",
    "Santa Clara County AOR",
    "Southland Reg. AOR",
    "Burbank Association of Realtors",
    "CLAW-Combined LA Westside MLS",
    "Mountain Communities",
    "Greater Palm Springs - CA",
  ],
  "Western Wisconsin Realtors Assoc": [
    "Fargo Moorhead Area AOR",
    "Realtor Assoc of So Minnesota",
    "St Cloud Area AOR",
    "Lake Superior Area Realtors",
  ],
  "Williamson County AOR": [
    "Victoria Area AOR",
    "Four Rivers AOR",
    "Fort Hood Area AOR",
    "Temple Belton BOR",
  ],
  "Williston Board of REALTORS": ["Bismarck Mandan BOR"],
  "Wiregrass MLS": [
    "Covington Board of REALTORS",
    "Southeast Alabama AOR - AL",
    "Pike County Board of REALTORS",
  ],
  "Yosemite Gateway AOR": [
    "Merced County AOR",
    "Fresno Association of Realtors",
    "Madera County AOR",
  ],
};
